services:
  ssl-monitor:
    image: iankulin/ssl-monitor:latest
    container_name: ssl-monitor
    ports:
      - "8080:8080"
    volumes:
      # Bind mount data directory to persist configuration and results
      - ./data:/app/data
    environment:
      - TZ=Australia/Perth
      - LOG_LEVEL=WARNING
    restart: unless-stopped