services:
  ssl-monitor:
    build: .
    container_name: ssl-monitor
    ports:
      - "80:8080"
    volumes:
      # Bind mount data directory to persist configuration and results
      - ./data:/app/data
    environment:
      - TZ=Australia/Perth
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
